---
- name: install packages
  apt:
    name:
    - network-manager
    - openconnect
    - dante-server
    - net-tools
    state: present
    update_cache: yes

- name: set up NetworkManager to manage network interfaces
  lineinfile:
    path: /etc/NetworkManager/NetworkManager.conf
    regexp: '^managed='
    line: managed=true
  notify:
  - network-manager

- name: set up NetworkManager to manager devices
  lineinfile:
    path: /usr/lib/NetworkManager/conf.d/10-globally-managed-devices.conf
    regexp: '^unmanaged-devices='
    line: unmanaged-devices=*,except:type:vpn,except:type:ethernet
  notify:
  - network-manager

- meta: flush_handlers

- name: check if eth0 connection exists
  shell: nmcli c | tail -n +2 | awk '{print $1}' | grep eth0 | cat
  register: eth0_connection

- name: shutdown existing eth0 connection
  shell: nmcli c down eth0
  when: eth0_connection.stdout | length > 0

- name: copy dante-server configuration
  copy:
    src: danted.conf
    dest: /etc/danted.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: set up dante-servewr systemd service for logging
  lineinfile:
    path: /lib/systemd/system/danted.service
    insertbefore: "^InaccessibleDirectories="
    line: "ReadWritePaths=/var/log"

- name: reload systemd daemon
  systemd:
    daemon_reload: yes

- name: create empty log file for dante-server
  file:
    path: /var/log/sockd.log
    owner: root
    group: root
    mode: '0644'
    state: touch

- name: copy vpn control scripts
  template:
    src: "{{ item }}.j2"
    dest: "/usr/local/bin/{{ item }}"
    owner: vagrant
    group: vagrant
    mode: '0755'
  loop:
  - vpn-up
  - vpn-down
